version: '3'

services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: postgres
    web:
        build: .
        command: ["make", "start"]
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db